# 1. Numpy数组


## 1.1. 从已有数据中创建数组

In [3]:
import numpy as np

### 1.1.1. list $\rightarrow$ ndarray

In [5]:
list_1 = [i for i in range(5)]
ndarray_1 = np.array(list_1)
print(ndarray_1, type(ndarray_1))

list_2 = [[i for i in range(0, 6)], [i for i in range(5,11)]]
ndarray_2 = np.array(list_2)
print(ndarray_2, type(ndarray_2))

[0 1 2 3 4] <class 'numpy.ndarray'>
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]] <class 'numpy.ndarray'>


## 1.2. np.random

|函数|描述|
|---|---|
|`np.random.random`|生成0到1之间的随机数（均匀分布）|
|`np.random.uniform`|生成均匀分布的随机数|
|`np.random.randn`|生成标准正态分布的随机数|
|`np.random.randint`|生成随机整数|
|`np.random.normal`|生成正态分布|
|`np.random.shuffle`|随机打乱顺序|
|`np.random.seed`|设置随机数种子|
|`random_sample`|生成随机的浮点数|

In [6]:
nd3 = np.random.random([3, 3])
print(nd3, nd3.shape)

# 为了每次生成同一份数据，可以指定一个随机种子，使用shuffle打乱生成的随机数
np.random.seed(114514)
nd4 = np.random.randn(2, 3)
print(nd4)
np.random.shuffle(nd4)
print(nd4)
print(type(nd4))

[[0.15555461 0.00823713 0.07603428]
 [0.74283921 0.92969568 0.77081494]
 [0.50193596 0.6742566  0.81565758]] (3, 3)
[[ 1.11490901  1.1882115   1.41804512]
 [-0.36769038  0.24881411  0.38049812]]
[[ 1.11490901  1.1882115   1.41804512]
 [-0.36769038  0.24881411  0.38049812]]
<class 'numpy.ndarray'>


## 1.3. 创建特定形状的多维数组

|函数|描述|
|---|---|
|`np.zeros`|创建特定尺寸的全0数组|
|`np.ones`|创建特定尺寸的全1数组|
|`np.empty`|创建特定尺寸的数组（初值为垃圾值）|
|`np.zeros_like`|创建相同维度的全0数组|
|`np.ones_like`|创建相同维度的全1数组|
|`np.empty_like`|创建相同维度的数组（初值为垃圾值）|
|`np.eye`|创建一个特定尺寸的对角线数组|
|`np.full`|创建一个特定尺寸的全初始化值数组|

In [9]:
nd5 = np.zeros((3, 3))
nd6 = np.ones((3, 3))
nd7 = np.eye(3)
nd8 = np.diag([1, 2, 3])

print("{} \n\n {} \n\n {} \n\n {}".format(nd5, nd6, nd7, nd8))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## 1.4. arange / linspace

```python
arange([start,] stop[,step,], dtype=None)
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

In [11]:
print(np.arange(10), \
np.arange(0,10), \
np.arange(1,4,0.5), \
np.arange(9,-1,-1))

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] [1.  1.5 2.  2.5 3.  3.5] [9 8 7 6 5 4 3 2 1 0]


In [12]:
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
