# 2. numpy索引

In [2]:
import numpy as np 
np.random.seed(2019) 
nd11 = np.random.random([10]) #获取指定位置的数据，获取第4个元素 
print(nd11[3]) #截取一段数据 
print(nd11[3:6]) #截取固定间隔数据 
print(nd11[1:6:2]) #倒序取数 
print(nd11[::-2]) #截取一个多维数组的一个区域内数据 
nd12=np.arange(25).reshape([5,5]) 
print(nd12[1:3,1:3]) #截取一个多维数组中，数值在一个值域之内的数据 
print(nd12[(nd12>3)&(nd12<10)]) #截取多维数组中，指定的行,如读取第2,3行 
print(nd12[[1,2]]) #或nd12[1:3,:] 
##截取多维数组中，指定的列,如读取第2,3列 
print(nd12[:,1:3])

0.6378774010222266
[0.6378774  0.88049907 0.29917202]
[0.39308051 0.6378774  0.29917202]
[0.4057498  0.90320616 0.29917202 0.6378774  0.39308051]
[[ 6  7]
 [11 12]]
[4 5 6 7 8 9]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


还可以通过函数实现对数组的索引

In [3]:
from numpy import random as nr 
a=np.arange(1,25,dtype=float) 
c1=nr.choice(a,size=(3,4)) #size指定输出数组形状 
c2=nr.choice(a,size=(3,4),replace=False) #replace缺省为True，即可重复抽取。 
#下式中参数p指定每个元素对应的抽取概率，缺省为每个元素被抽取的概率相同。 
c3=nr.choice(a,size=(3,4),p=a / np.sum(a)) 
print("随机可重复抽取") 
print(c1) 
print("随机但不重复抽取") 
print(c2) 
print("随机但按权重概率抽取") 
print(c3)

随机可重复抽取
[[19.  6. 24. 22.]
 [21. 17. 16.  2.]
 [23. 15. 13. 11.]]
随机但不重复抽取
[[ 5. 14. 23. 15.]
 [ 8. 24.  6. 18.]
 [13. 10. 21. 11.]]
随机但按制度概率抽取
[[19. 21. 18. 11.]
 [10. 21. 23. 19.]
 [18. 19. 11. 20.]]
