# 3. 算术运算

In [1]:
import numpy as np

## 3.1. 对应元素相乘 / 逐元乘法 / Element Wise Product

```python
numpy.multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'multiply'>
```

Multiply arguments element-wise.

**Parameters**:

``x1, x2``: array_like
输入要相乘的数组。如果形状不相等时，它们必须可广播到公共形状(这将成为输出的形状)。

``out``: ndarray, None, or tuple of ndarray and None, optional
存储结果的位置。如果提供，它必须具有输入广播到的形状。如果未提供或为None，则返回一个新分配的数组。元组(只能作为关键字参数)的长度必须等于输出的数量。

``where``: array_like, optional
这个条件在输入上广播。在条件为True的位置，out数组将被设置为ufunc的结果。在其他地方，out数组将保留其原始值。注意，如果通过默认的out=None创建一个未初始化的out数组，那么其中条件为False的位置将保持未初始化。

``**kwargs``
For other keyword-only arguments, see the ufunc docs.

**Returns**:

``yn``: darray
x1和x2的乘积。如果x1和x2都是标量，这就是标量。

In [2]:
A = np.array([[1, 2], [-1, 4]]) 
B = np.array([[2, 0], [3, 4]]) 
print(A*B) #结果如下： array([[ 2, 0], [-3, 16]]) 
#或另一种表示方法 

print(np.multiply(A,B)) #运算结果也是 array([[ 2, 0], [-3, 16]])

[[ 2  0]
 [-3 16]]
[[ 2  0]
 [-3 16]]


## 3.2. 点积运算

点积运算（Dot Product）又称为内积，在Numpy用``np.dot``表示，其一般 格式为：

```python
numpy.dot(a, b, out=None)
```

In [3]:
X1=np.array([[1,2],[3,4]]) 
X2=np.array([[5,6,7],[8,9,10]]) 
X3=np.dot(X1,X2) 
print(X3)

[[21 24 27]
 [47 54 61]]
